# frozen_string_literal: true

require_relative "vibe/mixin/alignment_helpers"
require_relative "vibe/mixin/spec_file_helper"

require_relative "vibe/attr_order"
require_relative "vibe/blank_line_after_assignment"
require_relative "vibe/blank_line_before_expectation"
require_relative "vibe/class_organization"
require_relative "vibe/consecutive_assignment_alignment"
require_relative "vibe/consecutive_constant_alignment"
require_relative "vibe/consecutive_indexed_assignment_alignment"
require_relative "vibe/consecutive_instance_variable_assignment_alignment"
require_relative "vibe/consecutive_let_alignment"
require_relative "vibe/describe_block_order"
require_relative "vibe/explicit_return_conditional"
require_relative "vibe/is_expected_one_liner"
require_relative "vibe/keyword_argument_order"
require_relative "vibe/let_order"
require_relative "vibe/multiline_hash_argument_style"
require_relative "vibe/no_assigns_attribute_testing"
require_relative "vibe/no_compound_conditions"
require_relative "vibe/no_rubocop_disable"
require_relative "vibe/no_skipped_tests"
require_relative "vibe/no_unless_guard_clause"
require_relative "vibe/prefer_one_liner_expectation"
require_relative "vibe/raise_unless_block"
require_relative "vibe/rspec_before_block_style"
require_relative "vibe/rspec_stub_chain_style"
require_relative "vibe/service_call_method"
